on: [push]
jobs:
  build-and-deploy:
    runs-on: docker
    container:
      image: mcr.microsoft.com/playwright:v1.62.1-noble
      # should be node 24 implicitly
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
      CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache npm
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('web/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: Build
        run: |
          cd web
          npm ci
          npx ng build
      
      - name: Test
        run: |
          cd web
          npx ng test --no-watch --no-progress
      - name: Build and deploy to preview
        if: github.ref == 'refs/heads/dev'
        run: |
          cd web
          npm run patch-webmanifest "imDCC PRE" "intermodalDCC PREVIEW"
          npx ng build
          npx wrangler pages deploy --project-name intermodaldcc --branch dev ./dist/web/browser/
      - name: Build and deploy to prod
        if: github.ref == 'refs/heads/main'
        run: |
          cd web
          npm run patch-webmanifest "intermodalDCC" "intermodalDCC"
          npx ng build
          npx wrangler pages deploy --project-name intermodaldcc --branch main ./dist/web/browser/